font_family                 Hack Nerd Font
bold_font                   auto
italic_font                 auto
bold_italic_font            auto
font_size                   12.0

macos_dock_badge_on_bell    yes
macos_option_as_alt         left

map shift+enter send_text all \x1b\r

window_padding_width        4.0
scrollback_lines            10000
wheel_scroll_multiplier     3.0

background_opacity          0.95
dynamic_background_opacity  yes

background                  #101010
foreground                  #d4d4d4
cusror                      #ffffff
cursor_text_color           #343434
selection_background        #232323
selection_foreground        #d4d4d4

color0                      #1C1C1C
color1                      #FF8080
color2                      #99FFE4
color3                      #FFC799
color4                      #A0A0A0
color5                      #FFCFA8
color6                      #99FFE4
color7                      #CFCFCF
color8                      #505050
color9                      #FF9A9A
color10                     #B8FFF0
color11                     #FFCFA8
color12                     #D0D0D0
color13                     #FFB0B0
color14                     #B8FFF0
color15                     #FFFFFF
