# TODO: Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font xft:URWGothic-Book 11

# Configure border style <normal|1pixel|pixel xx|none|pixel>
default_border pixel 1
default_floating_border normal

# Hide borders
hide_edge_borders on

# Disable all applications top bars
for_window [class="^.*"] border pixel 1

# Set inner/outer gaps
gaps inner 14
gaps outer -2

# Smart gaps (gaps used if only more than one container on the workspace)
smart_gaps on

# Smart borders (draw borders around container only if it is not the only container on this workspace) 
# on|no_gaps (on=always activate and no_gaps=only activate if the gap size to the edge of the screen is 0)
smart_borders on

# Status bar
bar {
	i3bar_command i3bar
	status_command i3status
	position bottom
    tray_output primary

	bindsym button4 nop
	bindsym button5 nop

#   font xft:URWGothic-Book 11
	strip_workspace_numbers yes

    colors {
        background $term_color0
        statusline $term_color15
        separator  $term_color8

        #                  Boder        Background   Text
        focused_workspace  $term_color2 $term_color2 $term_color15
        active_workspace   $term_color0 $term_color0 $term_color15
        inactive_workspace $term_color0 $term_color0 $term_color8
        binding_mode       $term_color0 $term_color0 $term_color8
        urgent_workspace   $term_color1 $term_color1 $term_color15
    }
}

# Theme colors
# class                   border  backgr. text    indic.   child_border
  client.focused          $term_color2 $term_color2 $term_color15 $term_color15
  client.focused_inactive $term_color0 $term_color0 $term_color8 $term_color15
  client.unfocused        $term_color0 $term_color0 $term_color8 $term_color8
  client.urgent           $term_color1 $term_color1 $term_color15 $term_color15
  client.placeholder      $term_color0 $term_color0 $term_color15 $term_color15

  client.background       $term_color0
