#!/usr/bin/env bash

# Navigation aliases
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# ls aliases (color)
alias ls='ls --color=auto'
alias ll='ls -lh'
alias la='ls -lAh'
alias l='ls -CF'

# Safety nets aliases
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Vim aliases
alias vim='nvim'
alias v='nvim'

# Git aliases
alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline --graph --decorate'
alias gd='git diff'

# Terraform aliases
alias tf="terraform"
alias tfi="terraform init"
alias tfp="terraform plan"
alias tfa="terraform apply"

# Claude aliases
alias c="claude"

# Ollama aliases
alias o="ollama"
alias oc="ollama launch claude --model qwen3.5:latest"

# Reload bash alias
alias reload='source ~/.bash_profile'

# Claude Code usage aliases
alias ccud="npx ccusage daily --package"
alias ccum="npx ccusage monthly --package"

# macOS specific aliases
if [[ "$OSTYPE" == "darwin"* ]]; then
    alias finder='open -R'
    alias flushdns='sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder'
fi